import os
os.system('sudo apt-get update -y')
os.system('sudo apt-get install python-pip -y')
os.system('sudo pip install pip --upgrade')
os.system('sudo apt-get install python-numpy -y')
os.system('sudo pip install bottle beautifulsoup')
os.system('sudo pip install oauth2client')
os.system('sudo pip install --upgrade google-api-python-client')
os.system('sudo pip install beaker')
os.system('sudo pip install pyparsing')
os.system('sudo pip install filedepot')
os.system('sudo pip install selenium')
os.system('sudo apt-get install phantomjs -y')
os.system('sudo pip install tensorflow --no-cache-dir --ignore-installed')
